const organizations = [
  {
    id: 1,
    name: "Youth Services Bureau (YSB)",
    city: "ottawa",
    address: "2675 Queensview Dr, Ottawa, ON",
    phone: "(613) 729-1000",
    website: "https://ysb.ca",
    description: "Dignity-based shelter, transitional housing, and wraparound support for youth. Diversion-first intake model. No wrong door policy.",
    ageGroups: ["youth"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "housing", "food", "healthcare", "mental_health", "employment"],
    special: ["lgbtq", "indigenous", "fleeing_violence"],
    urgency: true,
    capacity: "Available",
    tags: ["youth", "shelter", "transitional housing", "mental health", "employment", "LGBTQ+", "Ottawa"]
  },
  {
    id: 2,
    name: "Cornerstone Women's Shelter",
    city: "ottawa",
    address: "178 George St, Ottawa, ON",
    phone: "(613) 789-4382",
    website: "https://cornerstonewomen.ca",
    description: "Emergency shelter for women and children fleeing domestic violence. Confidential intake options and women-only staffing are available.",
    ageGroups: ["adult", "senior", "youth"],
    genders: ["women"],
    services: ["shelter", "food", "mental_health", "legal", "children"],
    special: ["women_staff", "fleeing_violence", "children"],
    urgency: true,
    capacity: "Limited",
    tags: ["women only", "domestic violence", "women staff", "children", "legal aid", "Ottawa"]
  },
  {
    id: 3,
    name: "Ottawa Mission",
    city: "ottawa",
    address: "35 Waller St, Ottawa, ON",
    phone: "(613) 234-1155",
    website: "https://ottawamission.com",
    description: "Large multi-service shelter for adults. Provides emergency beds, meals, a healthcare clinic, and addiction recovery programs.",
    ageGroups: ["adult", "senior"],
    genders: ["men"],
    services: ["shelter", "food", "healthcare", "addiction", "mental_health"],
    special: ["disability"],
    urgency: true,
    capacity: "Available",
    tags: ["men", "shelter", "meals", "addiction", "healthcare", "accessible", "Ottawa"]
  },
  {
    id: 4,
    name: "Wabano Centre for Aboriginal Health",
    city: "ottawa",
    address: "299 Montreal Rd, Ottawa, ON",
    phone: "(613) 748-0657",
    website: "https://wabano.com",
    description: "Culturally safe health and wellness services for First Nations, Metis, and Inuit people. Offers mental health, addictions, and social supports.",
    ageGroups: ["youth", "adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["healthcare", "mental_health", "addiction", "food"],
    special: ["indigenous", "language"],
    urgency: false,
    capacity: "Available",
    tags: ["Indigenous", "First Nations", "Metis", "Inuit", "mental health", "addictions", "Ottawa"]
  },
  {
    id: 5,
    name: "The Shepherd of Good Hope",
    city: "ottawa",
    address: "153 Dalhousie St, Ottawa, ON",
    phone: "(613) 241-1752",
    website: "https://sghottawa.com",
    description: "Shelter and day services for adults experiencing homelessness. Includes meals, hygiene facilities, outreach, and harm reduction.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "food", "healthcare", "mental_health", "addiction"],
    special: ["disability", "language"],
    urgency: true,
    capacity: "Available",
    tags: ["shelter", "meals", "harm reduction", "mental health", "accessible", "Ottawa"]
  },
  {
    id: 6,
    name: "Interval House",
    city: "toronto",
    address: "36 Interval Way, Toronto, ON",
    phone: "(416) 924-1491",
    website: "https://intervalhouse.ca",
    description: "Emergency shelter and counselling for women and children fleeing abuse. Long-term support includes housing help, legal advice, and employment readiness.",
    ageGroups: ["adult", "youth"],
    genders: ["women"],
    services: ["shelter", "housing", "mental_health", "legal", "employment", "children"],
    special: ["women_staff", "fleeing_violence", "disability"],
    urgency: true,
    capacity: "Limited",
    tags: ["women only", "domestic violence", "women staff", "legal", "children", "Toronto"]
  },
  {
    id: 7,
    name: "Covenant House Toronto",
    city: "toronto",
    address: "20 Gerrard St E, Toronto, ON",
    phone: "(416) 598-4898",
    website: "https://covenanthousetoronto.ca",
    description: "Shelter, crisis care, and transitional programs for youth aged 16-24. Offers trauma-informed care, education support, and employment programs.",
    ageGroups: ["youth"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "housing", "food", "healthcare", "mental_health", "employment"],
    special: ["lgbtq", "fleeing_violence", "disability"],
    urgency: true,
    capacity: "Available",
    tags: ["youth", "16-24", "shelter", "LGBTQ+", "employment", "trauma-informed", "Toronto"]
  },
  {
    id: 8,
    name: "Fred Victor",
    city: "toronto",
    address: "145 Queen St E, Toronto, ON",
    phone: "(416) 364-8228",
    website: "https://fredvictor.org",
    description: "Shelter, housing, and community services for adults. Includes mental health support, harm reduction, and housing placement for complex needs.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "housing", "mental_health", "addiction", "healthcare"],
    special: ["disability", "lgbtq", "language"],
    urgency: true,
    capacity: "Available",
    tags: ["shelter", "housing", "mental health", "harm reduction", "accessible", "LGBTQ+", "Toronto"]
  },
  {
    id: 9,
    name: "Na-Me-Res (Native Men's Residence)",
    city: "toronto",
    address: "621 College St, Toronto, ON",
    phone: "(416) 762-8433",
    website: "https://nameres.org",
    description: "Shelter, transitional housing, and cultural support for Indigenous men. Offers traditional healing, mental health, and housing programs.",
    ageGroups: ["adult", "senior"],
    genders: ["men"],
    services: ["shelter", "housing", "mental_health", "addiction", "employment"],
    special: ["indigenous", "language"],
    urgency: false,
    capacity: "Limited",
    tags: ["Indigenous", "men", "shelter", "cultural healing", "housing", "Toronto"]
  },
  {
    id: 10,
    name: "The Lighthouse",
    city: "hamilton",
    address: "71 Rebecca St, Hamilton, ON",
    phone: "(905) 528-8861",
    website: "https://thelighthousehamilton.com",
    description: "Emergency shelter, meals, and wraparound supports for adults in Hamilton. Accessible building with disability accommodations.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "food", "healthcare", "mental_health"],
    special: ["disability", "language"],
    urgency: true,
    capacity: "Available",
    tags: ["shelter", "meals", "accessible", "disability", "Hamilton"]
  },
  {
    id: 11,
    name: "Mission Services Hamilton",
    city: "hamilton",
    address: "196 Wentworth St N, Hamilton, ON",
    phone: "(905) 528-7221",
    website: "https://missionservices.ca",
    description: "Men's emergency shelter, addiction recovery, transitional housing, and employment programs for adults.",
    ageGroups: ["adult", "senior"],
    genders: ["men"],
    services: ["shelter", "housing", "food", "addiction", "employment"],
    special: [],
    urgency: true,
    capacity: "Available",
    tags: ["men", "shelter", "addiction", "employment", "transitional housing", "Hamilton"]
  },
  {
    id: 12,
    name: "Women's Community House",
    city: "london",
    address: "PO Box 505, London, ON",
    phone: "(519) 642-3003",
    website: "https://wch.on.ca",
    description: "Shelter and support services for women and children escaping domestic violence. Offers counselling, legal support, and housing help.",
    ageGroups: ["adult", "youth"],
    genders: ["women"],
    services: ["shelter", "housing", "mental_health", "legal", "children", "food"],
    special: ["women_staff", "fleeing_violence", "disability", "language"],
    urgency: true,
    capacity: "Available",
    tags: ["women only", "domestic violence", "women staff", "children", "London"]
  },
  {
    id: 13,
    name: "Unity Project London",
    city: "london",
    address: "459 York St, London, ON",
    phone: "(519) 438-6421",
    website: "https://unityprojectlondon.ca",
    description: "Emergency shelter and transitional housing for adults experiencing homelessness. Provides case management, mental health support, and harm reduction services.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "housing", "mental_health", "addiction", "food"],
    special: ["disability", "lgbtq"],
    urgency: true,
    capacity: "Available",
    tags: ["shelter", "transitional housing", "harm reduction", "LGBTQ+", "London"]
  },
  {
    id: 14,
    name: "Street Haven",
    city: "toronto",
    address: "87 Pembroke St, Toronto, ON",
    phone: "(416) 967-6060",
    website: "https://streethaven.com",
    description: "Women-only shelter with an all-women staff team. Services include crisis support, housing help, addictions counselling, and peer support.",
    ageGroups: ["adult", "senior"],
    genders: ["women"],
    services: ["shelter", "housing", "mental_health", "addiction"],
    special: ["women_staff", "lgbtq", "disability"],
    urgency: true,
    capacity: "Available",
    tags: ["women only", "women staff", "LGBTQ+", "addiction", "peer support", "Toronto"]
  },
  {
    id: 15,
    name: "Participation House",
    city: "hamilton",
    address: "11 George St, Hamilton, ON",
    phone: "(905) 528-0281",
    website: "https://participationhouse.com",
    description: "Supportive housing and community inclusion programs for adults with developmental and physical disabilities experiencing homelessness or housing insecurity.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["housing", "healthcare", "mental_health"],
    special: ["disability"],
    urgency: false,
    capacity: "Limited",
    tags: ["disability", "developmental disability", "supportive housing", "Hamilton"]
  },
  {
    id: 16,
    name: "Journeys End Refugee Settlement",
    city: "hamilton",
    address: "425 York Blvd, Hamilton, ON",
    phone: "(905) 526-8100",
    website: "https://jerc.ca",
    description: "Settlement services, housing support, and community programs for newcomers and refugees at risk of homelessness.",
    ageGroups: ["youth", "adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["housing", "food", "employment", "legal", "healthcare"],
    special: ["language", "disability"],
    urgency: false,
    capacity: "Available",
    tags: ["refugees", "newcomers", "language support", "settlement", "Hamilton"]
  },
  {
    id: 17,
    name: "Kingston Youth Shelter",
    city: "kingston",
    address: "661 Montreal St, Kingston, ON",
    phone: "(613) 542-6672",
    website: "https://kingstonyouthshelter.org",
    description: "Emergency shelter and transitional housing for youth aged 16-21 in the Kingston area. Offers case management, life skills, and education support.",
    ageGroups: ["youth"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "housing", "food", "mental_health", "employment"],
    special: ["lgbtq"],
    urgency: true,
    capacity: "Available",
    tags: ["youth", "16-21", "shelter", "life skills", "education", "Kingston"]
  },
  {
    id: 18,
    name: "New Beginnings Kingston",
    city: "kingston",
    address: "400 Elliott Ave, Kingston, ON",
    phone: "(613) 548-4535",
    website: "#",
    description: "Transitional housing and support services for adults leaving correctional facilities or experiencing chronic homelessness. Employment and life skills programming.",
    ageGroups: ["adult"],
    genders: ["men"],
    services: ["housing", "employment", "mental_health", "addiction", "legal"],
    special: ["disability"],
    urgency: false,
    capacity: "Available",
    tags: ["transitional housing", "reintegration", "employment", "addiction", "Kingston"]
  },
  {
    id: 19,
    name: "Canadian Mental Health Association Ottawa",
    city: "ottawa",
    address: "1355 Bank St, Ottawa, ON",
    phone: "(613) 737-7791",
    website: "https://cmhaottawa.ca",
    description: "Mental health and addictions support services including housing programs, crisis intervention, and outreach for adults in Ottawa.",
    ageGroups: ["adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["mental_health", "housing", "addiction", "healthcare"],
    special: ["disability", "lgbtq", "language"],
    urgency: false,
    capacity: "Available",
    tags: ["mental health", "addiction", "housing", "crisis support", "LGBTQ+", "Ottawa"]
  },
  {
    id: 20,
    name: "The Scott Mission",
    city: "toronto",
    address: "502 Spadina Ave, Toronto, ON",
    phone: "(416) 923-8872",
    website: "https://scottmission.com",
    description: "Comprehensive services including meals, emergency shelter, clothing, children's programs, and housing support for families and individuals.",
    ageGroups: ["youth", "adult", "senior"],
    genders: ["women", "men", "nonbinary"],
    services: ["shelter", "food", "housing", "healthcare", "children", "employment"],
    special: ["disability", "language", "fleeing_violence"],
    urgency: true,
    capacity: "Available",
    tags: ["families", "children", "meals", "shelter", "clothing", "Toronto"]
  }
];
